# Generated by Django 2.2.7 on 2020-09-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(verbose_name='用户id')),
                ('content', models.TextField(blank=True, help_text='记录的内容', null=True, verbose_name='内容')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
        ),
    ]
