# Generated by Django 2.2.7 on 2020-09-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personallog',
            name='userid',
            field=models.CharField(max_length=255, verbose_name='用户id'),
        ),
    ]
