# Generated by Django 2.2.7 on 2020-09-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20200927_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='personallog',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
    ]
