# Generated by Django 2.2.7 on 2020-09-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_personallog_is_true'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personallog',
            name='is_true',
        ),
    ]
