# Generated by Django 2.2.7 on 2020-09-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_remove_personallog_is_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255, verbose_name='用户id')),
                ('MediaId', models.TextField(verbose_name='通过素材管理中的接口上传多媒体文件，得到的id。')),
                ('PicUrl', models.TextField(verbose_name='图片链接（由系统生成）')),
                ('adminSet', models.BooleanField(default=False)),
            ],
        ),
    ]
